### ISSUE TITLE
Three asterisks just makes bold text, not bold italics

### ISSUE THREAD

**Issue by schro-from-tua** [tuataria/eve#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jwford** [comment]
this is smth wrong with your discord client on whatever device you were using
![image](https://user-images.githubusercontent.com/13416547/73224090-5ba80980-4136-11ea-8bde-7d41413c58f3.png)

**Comment by schro-from-tua** [comment]
Ah thanks. I’m using the Discord app on my iPhone with up-to-date software.
This is what it shows me when I use three asterisks on either side.
